troiswa_back_category:
    path: /
    defaults: { _controller:TroiswaBackBundle:Category:displayCategory }

troiswa_back_category_info:
    path: /{idcat}
    defaults: { _controller:TroiswaBackBundle:Category:displayInfoCategory }
    requirements:
        idcat: \d+

troiswa_back_category_add:
    path: /add
    defaults: { _controller:TroiswaBackBundle:Category:addCategory }
    requirements:
        idcat: \d+

troiswa_back_category_update:
    path: /update/{idcat}
    defaults: { _controller:TroiswaBackBundle:Category:updateCategory }
    requirements:
        idcat: \d+

troiswa_back_category_delete:
    path: /delete/{idcat}
    defaults: { _controller:TroiswaBackBundle:Category:deleteCategory }
    requirements:
        idcat: \d+
