troiswa_back_user:
    path:     /
    defaults: { _controller: "TroiswaBackBundle:User:index" }

troiswa_back_user_show:
    path:     /show/{id}
    defaults: { _controller: "TroiswaBackBundle:User:show" }

troiswa_back_user_new:
    path:     /new
    defaults: { _controller: "TroiswaBackBundle:User:new" }

troiswa_back_user_create:
    path:     /create
    defaults: { _controller: "TroiswaBackBundle:User:create" }
    methods:  POST

troiswa_back_user_edit:
    path:     /edit/{id}
    defaults: { _controller: "TroiswaBackBundle:User:edit" }

troiswa_back_user_edit_role:
    path:     /edit_role/{id}
    defaults: { _controller: "TroiswaBackBundle:User:editRole" }

troiswa_back_user_update:
    path:     /update/{id}
    defaults: { _controller: "TroiswaBackBundle:User:update" }
    methods:  [POST, PUT]

troiswa_back_user_delete:
    path:     /delete/{id}
    defaults: { _controller: "TroiswaBackBundle:User:delete" }
    methods:  [POST, DELETE]
