security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext

        #Symfony\Component\Security\Core\User\User:
                #    algorithm: sha512
                #    encode_as_base64: false
                #    iterations: 1

        Troiswa\BackBundle\Entity\User:
            algorithm: bcrypt
            cost: 15

        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_COMMERCIAL, ROLE_ALLOWED_TO_SWITCH]
        ROLE_COMMERCIAL: [ROLE_CLIENT]
        ROLE_CLIENT: [ROLE_USER]

    providers:
#        in_memory:
#            memory:
#                users:
#                    admin:
#                        password: toto
#                        roles: ROLE_ADMIN
#                    toto: { password: bidule, roles: ROLE_USER }
#                    toto: { password: 582fc805980c8508c75c6b162671552d6a468293d4070c03f82b849169c5e88ab1949558f938b98f212f5c53cfbf6a8c5d2401c69e63b9cfb0a6dcc92aae3ec7, roles: ROLE_USER }
        provider_back:
            #entity : { class: TroiswaBackBundle:User, property: pseudo }
            # Utilisation de UserRepository pour se connecter
            # Visualiser la méthode loadUserByUsername dans UserRepository pour mieux comprendre
            entity : { class: TroiswaBackBundle:User }

        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        login_firewall:
            pattern: ^/admin/login$
            anonymous: true

        front_login:
            pattern: ^/login$
            anonymous: true

        administration:
            pattern: ^/admin
            anonymous: true
#            http_basic:
#                realm: "Attention zone réservée"
#                provider: provider_back
            form_login:
                check_path: troiswa_back_login_check
                login_path: troiswa_back_login
                default_target_path: troiswa_back_administration
                always_use_default_target_path: true
#                csrf_provider: security.csrf.token_manager

            logout:
                path: troiswa_back_logout
                target: /admin

            provider: provider_back
#            switch_user: { role: ROLE_ADMIN, parameter: _want_to_be_this_user }
            # Pour permettre de switcher un utilisateur
            # ?_switch_user=toto changer d'utilisateur
            # ?_switch_user=_exit revenir sur mon utilisateur

            # se connecter en admin en tant qu'utilisateur toto
            # localhost/Symfony3wa/web/app_dev.php/admin/?_switch_user=toto
            switch_user: { role: ROLE_ADMIN }

            remember_me:
                key: "%secret%"
                lifetime: 172800 # 2 jours
                path: / # accessible sur toutes les urls
                domain: ~ #valeur par défaut : accessible partout sur mon site

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4

            logout: true
            anonymous: true

            remember_me:
                key: "%secret%"
                lifetime: 172800 # 2 jours
                path: / # accessible sur toutes les urls
                domain: ~ #valeur par défaut : accessible partout sur mon site

    access_control:
#         seul l'administrateur à accès aux pages produit
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_CLIENT }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#         seul l'administrateur à accès aux pages des utilisateurs
#        - { path: ^/admin/user, role: ROLE_ADMIN }

#        main:
#            anonymous: ~