<?php

namespace Troiswa\FrontBundle\Repository;

use Troiswa\BackBundle\Repository\CategoryRepository as CategBackRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends CategBackRepository
{


}
