<?php

namespace Troiswa\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    public function findCommentsOfProduct($idprod){

        $query= $this->createQueryBuilder('comment');

        // ATTENTION : les paramètres de la requête sont mappés avec les propriétés des entités
        // Et NON avec les champs des tables de la base de données
        $query->where("comment.product = :productId")
              ->setParameter("productId",$idprod);

        return $query;
    }





}