<?php

namespace Troiswa\BackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    public function findCategoryByPosition()
    {
        $query= $this->createQueryBuilder("categ");

        $query->select('categ')
              ->orderBy('categ.position','asc');

        $result = $query->getQuery()->getResult();

//        dump($result);
//        die();

        return $result;

    }



}
